{"name": "test_otp_verification_with_invalid_otp", "status": "passed", "steps": [{"name": "THis test verifies that OTP can't be validated with invalid code", "status": "passed", "start": 1648797476448, "stop": 1648797476978}], "start": 1648797476447, "stop": 1648797476978, "uuid": "b70b05bf-6584-4936-803c-16c6e560d8cc", "historyId": "9c05cad699f92058f0d2843b7c5a1d47", "testCaseId": "d2b3c2b5af37dee5291eb52a968eb4d5", "fullName": "tests.api_testcases.verify_otp.verify_otp_test.TestVerifyEmail#test_otp_verification_with_invalid_otp", "labels": [{"name": "parentSuite", "value": "tests.api_testcases.verify_otp"}, {"name": "suite", "value": "verify_otp_test"}, {"name": "subSuite", "value": "TestVerifyEmail"}, {"name": "host", "value": "pop-os"}, {"name": "thread", "value": "104538-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_testcases.verify_otp.verify_otp_test"}]}